name: Trigger QA Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dispatch-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger QA Repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN_FOR_QA }}
          repository: rucsacman/qa_testing_automation
          event-type: trigger-api-tests
          client-payload: |
            {
              "ref": "${{ github.head_ref }}",
              "sha": "${{ github.event.pull_request.head.sha }}",
              "pr_number": "${{ github.event.number }}",
              "repo_name": "${{ github.repository }}",
              "actor": "${{ github.actor }}",
              "target_url": "https://staging-api.your-domain.com"
            }

      - name: Wait for QA Status
        uses: WyriHaximus/github-action-wait-for-status@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          waitForCheck: "QA / API Automation"
          checkInterval: 10

      - name: QA Passed
        if: success()
        run: echo "QA Passed!"

      - name: QA Failed
        if: failure()
        run: |
          echo "❌ QA Failed!"
          exit 1
